[geral]
seed = 42
tempo-maximo = 60

[grafico]
exibir = false

[modelos.centro-distribuicao]
qtd-caminhoes = 5
qtd-vans = 4
qtd-funcionarios = 6
tamanho-caminhao = 20 # m³
tamanho-van = 8 # m³
tamanho-deposito = 300 # m³

[modelos.bar-expresso]
qtd-cadeiras = 6
qtd-funcionarios = 2
qtd-copos = 20
qtd-copos-pia = 6
